name: Release Android

on:
  workflow_dispatch: # Allows manual triggering
  push:
    tags:
      - 'v*' # Runs when a version tag like v1.0.0 is pushed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install NativeScript CLI
        run: npm install -g nativescript

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          cache: gradle
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install dependencies
        run: npm install

      - name: Extract versionName from app.gradle
        id: version
        run: |
          version=$(grep -oP 'versionName "\K[^"]+' App_Resources/Android/app.gradle)
          echo "VERSION_NAME=$version" >> $GITHUB_ENV

      - name: Decode keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 -d > my-release-key.keystore

      - name: Build APK
        run: |
            ns build android --release --env.snapshot --env.compileSnapshot --env.uglify --env.aot \
              --key-store-path my-release-key.keystore \
              --key-store-password ${{ secrets.KEYSTORE_PASSWORD }} \
              --key-store-alias ${{ secrets.KEY_ALIAS }} \
              --key-store-alias-password ${{ secrets.KEY_PASSWORD }}

      - name: Rename and collect APK
        run: |
          mkdir release_apks
          new_name="NeoComment-${VERSION_NAME}.apk"
          mv "platforms/android/app/build/outputs/apk/release/app-arm64-v8a-release.apk" "release_apks/$new_name"
          echo "Renamed: $new_name"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: NeoComment-${{ env.VERSION_NAME }}-APK
          path: release_apks/NeoComment-${{ env.VERSION_NAME }}.apk
